heat_template_version: "2017-09-01"
description: "simple cirros vm"
resources:
  floating_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: public
  inst1:
    type: OS::Nova::Server
    properties:
      flavor: m1.nano
      image: cirros-0.4.0-x86_64-disk
      networks:
        - network: private
  association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: floating_ip }
      server_id: { get_resource: inst1 }
