heat_template_version: "2017-09-01"
description: "simple cirros vm"
resources:
  internal_net:
    type: OS::Neutron::Net
  internal_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: internal_net }
      cidr: "10.8.1.0/24"
      dns_nameservers: [ "8.8.8.8" ]
      ip_version: 4
  internal_router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info: { network: public }
  internal_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: internal_router }
      subnet: { get_resource: internal_subnet }     
  secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          port_range_min: 22
          port_range_max: 22
        - protocol: icmp
          remote_ip_prefix: 0.0.0.0/0
  instance_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: internal_net }
      fixed_ips:
        - subnet_id: { get_resource: internal_subnet }
      security_groups:
        - default
        - { get_resource: secgroup }
  inst1:
    type: OS::Nova::Server
    properties:
      flavor: m1.nano
      image: cirros-0.4.0-x86_64-disk
      networks:
        - port: { get_resource: instance_port }
  floating_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: public
  association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: floating_ip }
      server_id: { get_resource: inst1 }

