heat_template_version: "2017-09-01"
description: "simple cirros vm"
resources:
  inst-1:
    type: OS::Nova::Server
    properties:
      flavor: m1.nano
      image: cirros-0.4.0-x86_64-disk
      networks:
        - network: private
